import type { CodePage } from '../CodePage';

/**
 * Windows-1258 (CP1258, "Windows Vietnamese") — standard Microsoft code page. Bytes 0x81, 0x8A,
 * 0x8D, 0x8E, 0x8F, 0x90, 0x9A, 0x9D, 0x9E are undefined in the standard and intentionally omitted.
 *
 * Five bytes (0xCC, 0xD2, 0xDE, 0xEC, 0xF2) hold Vietnamese combining tone marks (grave/hook
 * above/tilde/acute/dot below) rather than standalone letters — CP1258 composes a base Latin
 * letter followed by one of these bytes to render a toned vowel, since not every Vietnamese
 * vowel+tone combination has its own single-byte slot.
 *
 * Values cross-checked against the WHATWG "windows-1258" mapping shipped in this repo's own
 * iconv-lite dependency (node_modules/iconv-lite/encodings/sbcs-data-generated.js).
 */
export const Windows1258: CodePage = {
  id: 1258,
  name: 'Windows1258',
  chars: {
    0x80: '€',
    0x82: '‚',
    0x83: 'ƒ',
    0x84: '„',
    0x85: '…',
    0x86: '†',
    0x87: '‡',
    0x88: 'ˆ',
    0x89: '‰',
    0x8b: '‹',
    0x8c: 'Œ',
    0x91: '‘',
    0x92: '’',
    0x93: '“',
    0x94: '”',
    0x95: '•',
    0x96: '–',
    0x97: '—',
    0x98: '˜',
    0x99: '™',
    0x9b: '›',
    0x9c: 'œ',
    0x9f: 'Ÿ',
    0xa0: ' ',
    0xa1: '¡',
    0xa2: '¢',
    0xa3: '£',
    0xa4: '¤',
    0xa5: '¥',
    0xa6: '¦',
    0xa7: '§',
    0xa8: '¨',
    0xa9: '©',
    0xaa: 'ª',
    0xab: '«',
    0xac: '¬',
    0xad: '­',
    0xae: '®',
    0xaf: '¯',
    0xb0: '°',
    0xb1: '±',
    0xb2: '²',
    0xb3: '³',
    0xb4: '´',
    0xb5: 'µ',
    0xb6: '¶',
    0xb7: '·',
    0xb8: '¸',
    0xb9: '¹',
    0xba: 'º',
    0xbb: '»',
    0xbc: '¼',
    0xbd: '½',
    0xbe: '¾',
    0xbf: '¿',
    0xc0: 'À',
    0xc1: 'Á',
    0xc2: 'Â',
    0xc3: 'Ă',
    0xc4: 'Ä',
    0xc5: 'Å',
    0xc6: 'Æ',
    0xc7: 'Ç',
    0xc8: 'È',
    0xc9: 'É',
    0xca: 'Ê',
    0xcb: 'Ë',
    0xcc: '̀', // combining grave accent (huyền)
    0xcd: 'Í',
    0xce: 'Î',
    0xcf: 'Ï',
    0xd0: 'Đ',
    0xd1: 'Ñ',
    0xd2: '̉', // combining hook above (hỏi)
    0xd3: 'Ó',
    0xd4: 'Ô',
    0xd5: 'Ơ',
    0xd6: 'Ö',
    0xd7: '×',
    0xd8: 'Ø',
    0xd9: 'Ù',
    0xda: 'Ú',
    0xdb: 'Û',
    0xdc: 'Ü',
    0xdd: 'Ư',
    0xde: '̃', // combining tilde (ngã)
    0xdf: 'ß',
    0xe0: 'à',
    0xe1: 'á',
    0xe2: 'â',
    0xe3: 'ă',
    0xe4: 'ä',
    0xe5: 'å',
    0xe6: 'æ',
    0xe7: 'ç',
    0xe8: 'è',
    0xe9: 'é',
    0xea: 'ê',
    0xeb: 'ë',
    0xec: '́', // combining acute accent (sắc)
    0xed: 'í',
    0xee: 'î',
    0xef: 'ï',
    0xf0: 'đ',
    0xf1: 'ñ',
    0xf2: '̣', // combining dot below (nặng)
    0xf3: 'ó',
    0xf4: 'ô',
    0xf5: 'ơ',
    0xf6: 'ö',
    0xf7: '÷',
    0xf8: 'ø',
    0xf9: 'ù',
    0xfa: 'ú',
    0xfb: 'û',
    0xfc: 'ü',
    0xfd: 'ư',
    0xfe: '₫',
    0xff: 'ÿ',
  },
};
