package com.ndtcorepos.thermalprinter.error;

public enum PrinterErrorCode {
    NONE,
    INVALID_ARGUMENT,
    UNSUPPORTED_CONNECTION,

    PRINTER_NOT_FOUND,
    PRINTER_BUSY,

    PERMISSION_DENIED,
    PERMISSION_REQUIRED,

    DISCOVERY_FAILED,
    CONNECTION_FAILED,
    CONNECTION_TIMEOUT,

    NOT_CONNECTED,
    WRITE_FAILED,
    WRITE_TIMEOUT,

    USB_DEVICE_NOT_FOUND,
    USB_ENDPOINT_NOT_FOUND,
    USB_INTERFACE_CLAIM_FAILED,

    BLUETOOTH_DEVICE_NOT_FOUND,
    BLUETOOTH_CONNECTION_FAILED,

    NETWORK_CONNECTION_FAILED,
    NETWORK_TIMEOUT,

    JOB_CANCELLED,
    UNKNOWN_ERROR
}
